service: notify-aws-cost-to-line
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1

functions:
  costNotifier:
    handler: src/costNotifier.handler
    events:
      # 日本時間で毎朝９時に定期実行
      - schedule: cron(0 0 * * ? *)
    environment:
      LINE_NOTIFY_TOKEN: ${ssm:LINE_NOTIFY_TOKEN_OF_AWS_COST}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ce:GetCostAndUsage
        Resource: '*'
